### ISSUE TITLE
IP  option doesn't work

### ISSUE THREAD

**Issue by Heathland** [akamai/EdgeAuth-Token-Python#3]
I'll excuse in advance, I'm not that advanced in Python, but it seems that the IP function (-i --ip) doesn't work as it fails.

I fixed mine (I think) changing the code on line 150:
`new_token.append('ip={0}'.format(self._escape_early(ip)))`
to 
`new_token.append('ip={0}'.format(self._escape_early(self.ip)))`
in  cms_edgeauth.py

**Comment by AstinCHOI** [comment]
@Heathland Thank you so much for reporting this issue. I just updated it.
